CREATE TEMP TABLE EXPRELS AS
  SELECT DISTINCT EXPERIMENTS.ID   AS EXPID,
                  RELTARGETS.LEMMA AS TOKEN1,
                  R2.LEMMA         AS TOKEN2,
                  RELTARGETS.TAG   AS TAG1,
                  R2.TAG           AS TAG2,
                  RELATIONS.CATEGORY AS CAT,
                  RELATIONS.SCORE AS SCORE
  FROM   RELATIONS,
         RELTARGETS,
         RELTARGETS AS R2,
         EXPERIMENTS
  WHERE  RELATIONS.TOKEN1 = RELTARGETS.LEMMA
         AND RELATIONS.TOKEN2 = R2.LEMMA;
