CREATE TEMP TABLE WIDTABLE AS
  SELECT WINDOWCOUNT.ID AS WID,
         TOKEN1LEMMA,
         TOKEN1TAG,
         LMI.LMI,
         LMI.EXPID,
         GCOUNT.ENTROPY
  FROM   WINDOWCOUNT,
         LMI,
         EXPERIMENTS,
         GCOUNT
  WHERE  EXISTS(SELECT 1
                FROM   RELTARGETS
                WHERE  RELTARGETS.LEMMA = WINDOWCOUNT.TOKEN1LEMMA
                       AND RELTARGETS.TAG = WINDOWCOUNT.TOKEN1TAG)
         AND LMI.WID = WINDOWCOUNT.ID
         AND LMI.EXPID = EXPERIMENTS.ID
         AND EXPERIMENTS.ID = GCOUNT.EXPID
         AND GCOUNT.LEMMA = WINDOWCOUNT.TOKEN2LEMMA
         AND GCOUNT.TAG = WINDOWCOUNT.TOKEN2TAG
         AND WINDOWCOUNT.TOKEN2TAG IN (SELECT TAG
                                       FROM   TAGLISTS
                                       WHERE  EXP_ID = EXPERIMENTS.ID);

CREATE INDEX WID3
  ON WIDTABLE(EXPID, TOKEN1LEMMA, TOKEN1TAG);