CREATE TABLE LEFTTEMP AS
  SELECT TOKEN1LEMMA     AS LEMMA,
         TOKEN1TAG       AS TAG,
         Sum(TUPLECOUNT) AS LC
  FROM   WINDOWCOUNT
  WHERE  TOKEN1LEMMA IN(SELECT LEMMA
                        FROM   RELTARGETS)
  GROUP  BY TOKEN1LEMMA,
            TOKEN1TAG;