CREATE TABLE ENTROPIES AS
  SELECT TOKEN2LEMMA        AS LEMMA,
         TOKEN2TAG          AS TAG,
         Cast(NULL AS REAL) AS ENTROPY
  FROM   WINDOWCOUNT
  GROUP  BY TOKEN2LEMMA,
            TOKEN2TAG;