CREATE TABLE GUPREP AS
SELECT EXPRELS.TOKEN1 AS LEMMA1,
       EXPRELS.TOKEN2 AS LEMMA2,
       EXPRELS.TAG1,
       EXPRELS.TAG2,
       CAT,
       EXPRELS.EXPID,
       COSINE_SIM,
       E1.E AS E1,
       E2.E AS E2,
       E1.LIM,
       Cast(1 - ( E1.E / E2.E ) AS REAL) AS EV,
       Cast(1 - COSINE_SIM AS      REAL) AS RECCOS
FROM   EXPRELS,
       COS_SIM,
       EVALUES AS E1,
       EVALUES AS E2
WHERE  EXPRELS.EXPID = COS_SIM.EXPID
AND    EXPRELS.EXPID = E1.EXPID
AND    EXPRELS.EXPID = E2.EXPID
AND    E1.LEMMA = EXPRELS.TOKEN1
AND    E1.TAG = EXPRELS.TAG1
AND    E2.LEMMA = EXPRELS.TOKEN2
AND    E2.TAG = EXPRELS.TAG2
AND    EXPRELS.TOKEN1 = COS_SIM.TOKEN1
AND    EXPRELS.TOKEN2 = COS_SIM.TOKEN2
AND    EXPRELS.TAG1 = COS_SIM.TAG1
AND    EXPRELS.TAG2 = COS_SIM.TAG2
AND    E1.LIM = E2.LIM;