DELETE FROM WINDOWCOUNT
WHERE  WINDOWCOUNT.TOKEN1LEMMA = '<nullLEMMA>'
        OR WINDOWCOUNT.TOKEN2LEMMA = '<nullLEMMA>'
        OR WINDOWCOUNT.TOKEN1LEMMA = '<unknown>'
        OR WINDOWCOUNT.TOKEN2LEMMA = '<unknown>'; 