DELETE FROM WINDOWS
WHERE  WINDOWS.TOKEN1LEMMA = '<nullLEMMA>'
        OR WINDOWS.TOKEN2LEMMA = '<nullLEMMA>'
        OR WINDOWS.TOKEN1LEMMA = '<unknown>'
        OR WINDOWS.TOKEN2LEMMA = '<unknown>'; 
