INSERT INTO TAGLISTS (TAG, EXP_ID)
SELECT DISTINCT TOKEN2TAG, 1 FROM WINDOWCOUNT;
INSERT INTO TAGLISTS (TAG, EXP_ID)
SELECT DISTINCT TOKEN2TAG, 2 FROM WINDOWCOUNT
WHERE TOKEN2TAG NOT LIKE 'V%';
INSERT INTO TAGLISTS (TAG, EXP_ID)
SELECT DISTINCT TOKEN2TAG, 3 FROM WINDOWCOUNT
WHERE TOKEN2TAG NOT LIKE 'AD%'
AND TOKEN2TAG NOT LIKE 'JJ%';