UPDATE WINDOWCOUNT
SET LMI = WINDOWCOUNT.TUPLECOUNT * Log ( WINDOWCOUNT.TUPLECOUNT * ( 1.0 *
       (
              SELECT C
              FROM   GCOUNT
              WHERE  WINDOWCOUNT.TOKEN2LEMMA = GCOUNT.LEMMA
              AND    WINDOWCOUNT.TOKEN2TAG = GCOUNT.TAG) *
       (
              SELECT C
              FROM   GCOUNT
              WHERE  WINDOWCOUNT.TOKEN1LEMMA = GCOUNT.LEMMA
              AND    WINDOWCOUNT.TOKEN1TAG = GCOUNT.TAG) /
       (
              SELECT SUM(N)
              FROM   GLOBALTEMP)))
  WHERE WINDOWCOUNT.TOKEN1LEMMA IN (SELECT RELTARGETS.LEMMA FROM RELTARGETS);